server:
  port: 8000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:toy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

jwt:
  jwtKey: gtK6Ga9gs0WNhvIqFSMqwJtpAUpChrfzDc//iqHMKgQ=